-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE pairs (
	id text NOT NULL,
	fsym text NOT NULL,
	tsym text NOT NULL,
	created timestamp with time zone NOT NULL,
	raw text NOT NULL,
	display text NOT NULL,
	PRIMARY KEY ( id )
);
